### ISSUE TITLE
Code available

### ISSUE THREAD

**Issue by DIPTIMISHRA** [amnesiack/CNNCDM3CIR#1]
When will be this code available, as the paper is published now

**Comment by amnesiack** [comment]
> When will be this code available, as the paper is published now

thanks, we will release the code soon. Due to this is a joint work with a company, we need to ask for their permission before we make anything publicly available.

**Comment by DIPTIMISHRA** [comment]
Thanks for the reply.
Can you please tell me the possible tentative time to be taken, to release the codes

**Comment by amnesiack** [comment]
> Thanks for the reply.
> Can you please tell me the possible tentative time to be taken, to release the codes

We have submitted the code to the company and they have an internal checking process. It's hard to predict how long this process will take.
If it is urgent, you could refer to the released code of our previous project. https://github.com/amnesiack/ICIP2018CDM
That one is only for demosaicking, basiclly this paper is an extention of that one.
